spring:
  datasource:
    username: root
    password: a3Lqziu2vqnAun
    url: jdbc:mysql://localhost:3306/movies

    servlet:
      multipart:
        max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: poseter/

base:
  url: "http://localhost:8080"